version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 1337:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
