CREATE DATABASE printer;

CREATE USER api_user WITH ENCRYPTED PASSWORD 'password';

GRANT CONNECT ON DATABASE printer TO api_user;
GRANT USAGE ON SCHEMA public TO api_user;

\c printer

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api_user;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO api_user;
