//! SeaORM Entity. Generated by sea-orm-codegen 0.1.3

pub use super::comments::Entity as Comments;
pub use super::files::Entity as Files;
pub use super::images::Entity as Images;
pub use super::posts::Entity as Posts;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
